name: rive_checkbox
description: Checkbox widget with two or three state animation with a Rive animation of your choice
version: 0.0.1
homepage: https://github.com/jaumard/rive_checkbox.git

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.7.8 <2.0.0"

dependencies:
  rive: ">=0.6.8 <1.0.0"

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
