name: rive_checkbox
description: Checkbox widget with two or three state animation with a Rive animation of your choice
version: 0.1.0
homepage: https://github.com/jaumard/rive_checkbox.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.7.8"

dependencies:
  rive: ">=0.7.0 <1.0.0"
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
